### ISSUE TITLE
WebGL not work.

### ISSUE THREAD

**Issue by Bian-Sh** [RageAgainstThePixel/com.utilities.async#15]
# Bug Report

## Overview
我尝试在逻辑中使用  Task.Delay ，但是打包成 webgl 后，Task.Delay 没有效果。
我测试了 2023.2.14f1c1、2022.3.17f1c1、2020.3.28f1c1 均不行
但是，我使用了 [WebGLThreadingPatcher](https://github.com/VolodymyrBS/WebGLThreadingPatcher)却是完全正常。

I tried using Task.Delay in Unity but it didn't work when built as WebGL. I tested it on versions 2023.2.14f1c1, 2022.3.17f1c1, and 2020.3.28f1c1 with no success. However, when I used  [WebGLThreadingPatcher](https://github.com/VolodymyrBS/WebGLThreadingPatcher), it worked perfectly fine.

by the way,when i use 2020.3.28f1c1 , i found this error:"Packages\com.utilities.async\Runtime\Async\AwaiterExtensions.cs(129,13): error CS0518: Predefined type 'System.IAsyncDisposable' is not defined or imported" ,Perhaps your language syntax is too modern.

## To Reproduce
1. download the project blow
2. change platform to webgl in buildsettings
3. build and play
4. See and check webgl  interaction behaviour

## Expected behavior
Task.Delay should work well.

## Additional context
[WebGL Task.zip](https://github.com/RageAgainstThePixel/com.utilities.async/files/14954427/WebGL.Task.zip)

**Comment by StephenHodgson** [comment]
Makes sense. Webgl is a workaround for this module. Use await new wait for seconds instead.
