### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/com.utilities.async#2]
This package should support WebGL but needs validation

**Comment by StephenHodgson** [comment]
Confirmed that WebGL is not supported, because of threading being disabled in WASM

**Comment by Cdddo** [comment]
Is it possible to use [UniTask](https://github.com/Cysharp/UniTask) to replace this library, in order to get WebGL support for packages that are dependent on this (e.g. open ai for unity)? I've used UniTask successfully for many WebGL projects.

**Comment by StephenHodgson** [comment]
I was looking at UnitTask to see what similar things they're doing, but as far as I can tell it'll still stall the main thread for long running tasks.

**Comment by StephenHodgson** [comment]
There cannot be too much of a difference

**Comment by StephenHodgson** [comment]
@Cdddo UniTask has the same limitation as this library
https://github.com/Cysharp/UniTask#threadpool-limitation

**Comment by StephenHodgson** [comment]
Personally I think UniTask is too bloated which is why I don't use it.

**Comment by StephenHodgson** [comment]
Discord thread discussing this development work: https://discord.com/channels/855294214065487932/1114208085154738317
